### ISSUE TITLE
ssh key and gitolite naming

### ISSUE THREAD

**Issue by kyse** [ericpaulbishop/redmine_git_hosting#10]
What's the deal with the naming conventions of the ssh keys and gitolite usernames?

hello redmine_kyse_1305304142_465473, the gitolite version here is 1.5.4-1ubuntu0.1 (Debian)

Wouldn't it make more sense to use the gitolite naming conventions.  For instance, I currently have kyse@server.pub and kyse@home.pub.  These are not throught the redmine plugin ssh keys because redmine and gitolite were installed before this plugin.  So all I have to do is use the kyse usename in the config file and I'll be able to access a table from both home and on the server itself.

The way i see the plugin setup right now, each key I enter under my redmine user generates a seperate ssh key username for gitolite instead of using the key name from redmine as it's naming convention.  Wouldn't it make sense to use redmine_username@keyname_from_redmine.pub.

This way, after I install this plugin ontop of an existing gitolite setup, and I want to use redmine to add my keys instead of the shell, I can continue to just use kyse as my username in the gitolite-admin/conf/gitolite.conf file.

In addition this would allow you to expand this as a feature to import existing public keys from gitolite-admin/keydir/ into your redmine user account.  So, for isntance, I'd goto my account page under redmine, click on import existing keys, and my list of keys would then also include kyse@server and kyse@home in addition to any I've already entered.

The only issue I see with this concept would be a security thing.  What if existing gitolite users are not currently using the redmine setup for that gitolite server.  If someone knew about it, they could create a redmine account with that username, import and gain access to some secret repo not on redmine.  Or what if the redmine username of someone didn't match the username the gitolite admin setup for their gitolite-admin username, the same scenario as before could be applied, plus they wouldn't get their keys they're looking for imported.

Perhaps a patch to redmine could be made to check the username of the existing keys vs the username desired.  If the username already exists under gitolite, it could force manual approval be required from the redmine site admin so they can confirm they have the correct user.  Or perhaps so way of authenticating via one of their existing ssh logins, but that's way beyond what I could dream of coding up at my level.

**Comment by ericpaulbishop** [comment]
That's not a bug -- that's a feature.  The numbers are time in unix epoch + microseconds when the key was created, and this ensures its uniqueness.  There is a very specific reason I'm doing it this way:  I have two instances of redmine on one server, sharing one instance of gitolite.  Given that setup I can have the same username in each instance of redmine, and each of those users has a key with the same name... using your scheme that would cause problems.  Setting the key to, by default, have a name that involves a unique component solves the problem that this conflict can cause.

Also, if you have some keys/projects in gitolite that are managed independent from redmine this randomness in the name helps ensure there isn't going to be a conflict.

**Comment by kyse** [comment]
I see your point.  Thanks. :)

**Comment by kyse** [comment]
You could always use username@siteaddy@identifier.pub btw.  Just trying to offer up suggestions cause I see possibilities of integrating the redmine site groups into the gitolite-admin config groups as well.

**Comment by ericpaulbishop** [comment]
I think a better strategy for doing that is to add a column to the group database table that has a unique identifier for the group gitolite keys in that group.

I can think of two cases where adding the siteaddy as part of the key wouldn't solve the problem (unless you're careful about the implementation): (1) a site that can be accessed via multiple domain names, in which case you get confusion and (2) sub-addresses on the same domain, e.g. www.abc.com/redmine1 and www.abc.com/redmine2.  In each case you could find ways around the issue, but you'd have to handle the edge cases, which would just be a pain.  Much cleaner to just have unique ids.

**Comment by kyse** [comment]
How do you handle @group flags within gitolite.conf file?  It looks like every time the plugin updates my config, it keeps the @admin for the gitolite-admin repo, but it destroys the definition above the repo listing.  In addition, you've got handling for daemon, that's cool, but it destroys gitweb permissions.  I was thinking it would be cool to have a check, if they want to enable gitweb on a repo in the settings as well, and if they check yes, a text box appears letting them type in the contents of the (git)~/repositories/reponame.git/description file for the gitweb description field.  Then it should just use your code to ssh into the git account, and create the file inside the repo.  I suggest this go through you're plugin and the db so you can pull the description you wrote back up, if you ever need to make the repo not public, then public again.  For whatever reason I noticed (when your patch deleted the gitweb username on the repo) when a repo is removed from the gitweb projects.list, it automatically deletes the description file.
