### ISSUE TITLE
Shell scripts in /tmp not compatible with multiple simultaneous installations.

### ISSUE THREAD

**Issue by kubitron** [ericpaulbishop/redmine_git_hosting#101]
In a system with multiple gitolite installations (and multiple redmine installations on different virtual hosts), the configuration of shell scripts in /tmp causes problems.

I suggest putting the scripts in RAILS_ROOT/tmp instead to isolate them within each installation:

```
    @@git_hosting_tmp_dir ||= Rails.root.join("tmp", "redmine_git_hosting")
```

**Comment by ericpaulbishop** [comment]
On the other hand, if you have multiple redmine installations and  a single gitolite installation shared, the current setup is better.

If you want to address this, the proper way to do it is to make the tmp directory a customizable setting on the plugin settings page.  This isn't a priority of mine right now, but if you'd care to implement it, I'd be happy to accept your patch.

**Comment by kubitron** [comment]
I would point out that putting the shell scripts in a directory associated with the redmine installation is much cleaner and makes it easier to put selinux labels on the scripts.  Why put the scripts in /tmp?  Why not make them generic (non-customized) and simply put them in a bin directory associated with the plugin?

**Comment by tommyblue** [comment]
For security reasons my /tmp folder is mounted with the noexec flag and the plugin doesn't work. I think that the temp path should be configurable through the init.rb file

**Comment by kubitron** [comment]
Use my version of the plugin.  While it is not configurable in the way you suggest, it puts the shell scripts in the /bin directory of the plugin (so that I can make selinux work).

Perhaps this works for you?  My version has a lot of other fixes as well:

https://github.com/kubitron/redmine_git_hosting/
