### ISSUE TITLE
Plugin-wide Setting to Disable Public Git Access

### ISSUE THREAD

**Issue by mutewinter** [ericpaulbishop/redmine_git_hosting#104]
I am deploying a private install of ChiliProject / redmine_git_hosting and I need to have everything managed by Git be private.

I don't want to use only private projects, as users should be able to see all the projects available on ChiliProject. I just want to force git to always use SSH, even for newly created projects.

My current solution is to disable the git-daemon on the server and to set [allow_anonymouse_read](https://github.com/ericpaulbishop/redmine_git_hosting/blob/master/app/controllers/git_http_controller.rb#L63) to always be false. It would be much cleaner if there were a setting in the Plugin that disabled the ability for Git Repositories to be set to HTTP / HTTP and Daemon support.

**Comment by ericpaulbishop** [comment]
This is a feature request, not a bug. If you want to implement it yourself feel free, but this is not a priority for me.
