### ISSUE TITLE
Support for Non-Fast Forward Push

### ISSUE THREAD

**Issue by mutewinter** [ericpaulbishop/redmine_git_hosting#105]
Currently redmine_git_hosting sets all users to `RW+` in the gitolite config file. Doing so means that any user can fast forward push the repository. It would be nice if it were possible to setup permissions based on the user's role in the project for who can fast forward push.

Here's [the documentation for gitolite's access controls](http://sitaramc.github.com/gitolite/doc/gitolite.conf.html#_basic_access_control) that I'm referring to.

**Comment by ericpaulbishop** [comment]
This is a feature request.  If you want to implement it yourself feel free, but this is not a priority for me.
