### ISSUE TITLE
Sub project repos not in sub directories

### ISSUE THREAD

**Issue by rcross** [ericpaulbishop/redmine_git_hosting#106]
I'm not sure the best way to summarize this issue. 

Basically, I can't quite understand why repos of subprojects are stored in a subdirectory. The project identifier has to be unique across the whole redmine instance, not just within the parent project namespace so there is not a need for the extra path. 

For me, this is also making it very difficult to migrate in some legacy repos with existing paths. (perhaps unrelated, but it would be great if there was a way for gitolite to follow symlinks)

Can someone point out where the code for subdirectories is? It would be great if there was a way of making this configurable if lots of people really want their repos in sub directories.

**Comment by rcross** [comment]
There is also something wrong here because of the behaviour when moving a project to a subproject of another project, it actually moves the repo to a subfolder which ensures the web interface still works (and changes the checkout instructions), but breaks any clones/checkouts of the repo since it is no longer at the same path. 

I think this is a serious bug even though it looks like someone has written code to make it work this way.

**Comment by ericpaulbishop** [comment]
This is the desired, expected for the plugin, because it is in my opinion the most logical and straightforward way to handle this.  If you want to change it, you'll have to fork the project and do it differently.  I will not consider changing it.

**Comment by rcross** [comment]
Thanks for such a quick response Eric. 

I understand that the way it is currently coded, this is obviously the way you intended it to work. Can you explain a bit more about why you feel this is the only logical way to handle this? 

IMHO, if you have all the repos live at the (relative to gitosis base directory) root directory level then it has a few aspects: 
- simple to work with other systems since this is the way many other similar programs work
- uniqueness is still guaranteed
- keeps urls short

My biggest concern is that by moving the repo when the redmine project is changed to a subproject (or from a subproject to one on the main level), then any existing clones get broken. I'm quite aware that you can easily fix this by adding a new remote to the cloned repo, but this really feels like the wrong thing to do. 
If the repo stayed in the same location on the file system, then the existing clones of that repo wouldn't be broken. 

Is there some other aspect of having the repos in a subdirectory that I am not understanding which makes it a requirement?

**Comment by kubitron** [comment]
To agree with Eric here: the current behavior provides a way to cleanly organize the repo (i.e. subdirectories). Presumably the reason for using sub-projects is to help organize the repos and it makes sense to reflect this organization in the urls.

(And -- presumably you are not changing the organization of your projects frequently?)

**Comment by dfyx** [comment]
I agree with Eric and kubitron. Subdirectories are what I would expect.

There should be an option to change this behavior, though. I'll have a look at it.

**Comment by rcross** [comment]
Considering that we are using gitolite/redmine to actually manage the repos, I don't really feel the need to exert additional organization at the file system level - especially at the expense of changes in redmine causing other people using the system to get errors. 

@dfyx - you can see my pull request https://github.com/ericpaulbishop/redmine_git_hosting/pull/108 which attempts to implement a configurable option for this. I think it works, but it needs to be reviewed since it might not be the best way to implement it.

**Comment by sduensin** [comment]
Eric, please consider adding rcross's patch for this issue.  I can see the merits of both directory layouts, but strongly prefer a flat arrangement for short URLs and non-breaking project reorganization.  Thanks for a great tool!

**Comment by sduensin** [comment]
@rcross - I applied your patches and it doesn't quite work.  It properly shows the shortened GIT URL but the HTTP URL has a double-slash in the middle.  Also, when I attempt to browse the repository in Redmine my logs show it trying to use the nested directory structure still.

I'm a Ruby n00b and not quite sure how to fix it myself.

**Comment by kubitron** [comment]
Since I tackled the subdirectory structure in my latest resilience patch, I decided to implement this feature in a slightly different way.  There is a select box for "Hierarchical" or "Flat" structure on the settings page.  You can move freely between the two and it will do the "right thing".  Also the URLs display should be fine as well. @rcross, no desire to step on your toes, but I happened to be fixing the path structure and decided to implement this feature.  

Please give this a try:

https://github.com/kubitron/redmine_git_hosting/

Don't forget to run:

rake db:migrate_plugins RAILS_ENV=production

After pulling the commits.

**Comment by anarcat** [comment]
I would join my voice to others here and request that this be made customizable. This would also encourage people like us that are stuck on the older gitosis plugin that has a flat namespace, and for which it would be a nightmare to migrate away... I identified [this commit](https://github.com/kubitron/redmine_git_hosting/commit/2f1c213c0ce41d024ad2b86585e4dea99c25b2c7) as being the one that introduces the "hierachy" setting, but it's a huge diff and I am not sure it's wise for us to use this in production.

@kubitron any way you can make a smaller patch for inclusion?

**Comment by kubitron** [comment]
Actually, I suggest that you just use my version of the plugin.  It is much more stable for a variety of reasons (the reason that the patch is so large).  

Others are switching as well (Eric doesn't seem to be maintaining this anymore). 

Use my master branch: https://github.com/kubitron/redmine_git_hosting/

The bottom line answer about the size of the commit is that I refactored the path handling code (to make it much more stable) and got the flat-hierarchy option "for free".  Note also that my version has an "access box" at the top of the settings page that shows you how your various settings choices affect the git and http access paths....

**Comment by anarcat** [comment]
Humm... according to the network view, eric committed to this plugin _yesterday_, so it hardly seems abandoned.. I'd be curious to try your branch though. Do you happen to be on IRC by any chance?

**Comment by kubitron** [comment]
p.s. I have had little to no success getting Eric to incorporate any changes that I make.  Simply adding the feature you request in a minimal fashion with the hope that Eric will add it to his version of the plugin is a lot of reworking of things for little additional benefit.  (And this current version of the plugin has lots of problems in real deployments which I fixed).

**Comment by kubitron** [comment]
Well, his master branch hasn't changed since October 13th.  I suppose you are referring to other branches... As for his responsiveness, I have been responding to bug reports on this site -- no one else seems to be doing that.

At any rate, give my plugin a try.  There may be some compatibility issues with Chili, since I use Redmine, but I am more than happy to fix them (have someone who seems signed up to do this at the moment).

I'm not really on IRC at the moment. However, you can send me email directly, if you wish.

**Comment by anarcat** [comment]
Alright, thank you. I have tried your plugin, but unfortunately both yours and eric's do not work in Redmine 1.1 anymore, so I have a huge leap to go through before we can install this (ie. the infamous Redmine 1.3 debian squeeze backport, which depends on the [rails backport](http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=657813), which is hard).

Our configuration notes are here: https://wiki.koumbit.net/RedmineGitolite

**Comment by kubitron** [comment]
So, what doesn't work?  I know that my plugin works for 1.2, so perhaps that is not as crazy a change for you?

At any rate, I started with Eric's version, so it is not surprising that we share a weakness with older versions of Redmine.  Do you have any specific log entries or failure behavior you can show me?  If you post an issue over on my plugin's homepage, I might be able to take a look...

**Comment by anarcat** [comment]
done: https://github.com/kubitron/redmine_git_hosting/issues/12
