### ISSUE TITLE
Allow for defining custom file path to project repo 

### ISSUE THREAD

**Issue by rcross** [ericpaulbishop/redmine_git_hosting#107]
There are 2 parts to this ticket. 

1) If you have repos already configured for some projects using the native functionality in redmine, and then install this plugin to help manage the repo permissions and repo creation, any repos that don't use the same machine name as the project (i.e. a custom path) then it gets broken 

2) There is no way to tell the plugin to use a non-standard file path (which would be helpful for pointing a project back to the original paths in the upgrade-style situation above or in a migration situation).

**Comment by ericpaulbishop** [comment]
A custom file path would defeat the purpose of using gitolite.  The gitolite path is already configurable.  Your request defeats the purpose of the plugin -- I will not consider changing this.

**Comment by rcross** [comment]
I am not sure how my request defeats the purpose of the plugin. Can you explain a bit further? 

I think you are right that in order for this to work, the "custom path" would have to be relative to the gitolite base path but I don't see a reason why you couldn't allow for a custom path that is relative to the gitolite base. 

As I mentioned, the current behaviour is destructive of existing repo information in the database at the time of installation which I think is very poor form.

For a fresh installation of redmine, these issues are not a problem of course but for any existing redmine instance that has projects already defined with some paths to git repos this is a problem. And for any situation where people have an existing gitolite configured or other repo system, there is no easy way to import the data if it doesn't follow the same identifier pattern in redmine. 

Since the path is stored in the table, is there no reason you couldn't expose this to the project settings form and allow the path to be overridden? are there other implications here that I do not see which would prevent this from being feasible?
