### ISSUE TITLE
public_keys_path

### ISSUE THREAD

**Issue by kyse** [ericpaulbishop/redmine_git_hosting#11]
Looks like your label_public_keys path leading to my/public_keys doesn't lead anywhere.. there's no page available to display here.

**Comment by ericpaulbishop** [comment]
I don't think there's any link to it anywhere -- the only place where that code is used is when editing a public key, and that works fine.  I'm not sure what you're saying doesn't work.  Is there a link that needs to be changed somewhere?

**Comment by ericpaulbishop** [comment]
I never got a response, as to what the actual error is, so I'm going to close this.
