### ISSUE TITLE
Viewing checkout URLs causes RoutingError

### ISSUE THREAD

**Issue by bradneuman** [ericpaulbishop/redmine_git_hosting#111]
I am running redmine 1.2.1.stable with redmine_git_hosting v0.4.2 on ubuntu 10.04.3. Everything works except for the checkout urls. I can check out and push to the repo's and add my ssh key using redmine, but the url bar is empty and my redmine log shows the following errors (with the traceback and my personal info cut):

```
Processing ApplicationController#index (for <MY IP> at 2011-10-18 13:57:30) [GET]

ActionController::RoutingError (No route matches "/plugin_assets/redmine_git_hosting/stylesheets/git_url_display.css" with {:method=>:get}):

Rendering /usr/share/redmine/public/404.html (404 Not Found)

Processing ApplicationController#index (for <MY IP> at 2011-10-18 13:57:31) [GET]

ActionController::RoutingError (No route matches "/plugin_assets/redmine_git_hosting/javascripts/git_url_display.js" with {:method=>:get}):

Rendering /usr/share/redmine/public/404.html (404 Not Found)

Processing ApplicationController#index (for <MY IP> at 2011-10-18 13:57:31) [GET]

ActionController::RoutingError (No route matches "/plugin_assets/redmine_git_hosting/stylesheets/zero_clipboard.css" with {:method=>:get}):

Rendering /usr/share/redmine/public/404.html (404 Not Found)

Processing ApplicationController#index (for <MY IP> at 2011-10-18 13:57:31) [GET]

ActionController::RoutingError (No route matches "/plugin_assets/redmine_git_hosting/javascripts/ZeroClipboard.js" with {:method=>:get}):

Rendering /usr/share/redmine/public/404.html (404 Not Found)

Processing ApplicationController#index (for <MY IP> at 2011-10-18 13:57:31) [GET]

ActionController::RoutingError (No route matches "/plugin_assets/redmine_git_hosting/javascripts/zero_clipboard_setup.js" with {:method=>:get}):

Rendering /usr/share/redmine/public/404.html (404 Not Found)

Processing ApplicationController#index (for <MY IP> at 2011-10-18 13:57:31) [GET]

ActionController::RoutingError (No route matches "/plugin_assets/redmine_git_hosting/images/paste.png" with {:method=>:get}):

Rendering /usr/share/redmine/public/404.html (404 Not Found)
```

I have redmine installed in a sub URI (/redmine) and I'm using Apache with Passenger. There are green checks next to each of the sudo checks in the plugin config page.

I am new to redmine and ruby on rails, so it's possible this is just a mistake on my part, but I've done my best to research the issue and ask elsewhere and haven't found a solution.

EDIT: I should also mention that if I turn off the "show checkout URLs" option, I receive no errors in the log and the pages load correctly

**Comment by bradneuman** [comment]
The same problem is showing up with other plugins, so this is probably just a configuration issue or possibly a redmine problem, but not specific to redmine_git_hosting

**Comment by jorgeazevedo** [comment]
For future reference, this can be fixed by creating a symbolic link

```
ln -s /var/cache/redmine/default/plugin_assets
```

in the `public` folder (in redmine's root).
