### ISSUE TITLE
Public Keys Enable/Delete

### ISSUE THREAD

**Issue by s0undt3ch** [ericpaulbishop/redmine_git_hosting#123]
I'd like to be able to actually delete the public keys in the database as oposed to disabling them, which, unless we do some sql, we can't re-enable them.

Any reason why the actual deletion of keys was not though in the first place?

**Comment by kubitron** [comment]
Actually, I think that the original intention was that inactive keys would be deleted right away, but some of the synchronization errors that were present would occasionally prevent this from happening.

At any rate, if you grab my master branch, I believe that it has the behavior you want, namely both deleting and "deactivating" from the edit page cause the keys to go away completely.  

This branch also fixes a number of other issues with performance and lack of synchronization between gitolite and redmine.

I'd love it if you give it a shot and give me feedback:

https://github.com/kubitron/redmine_git_hosting/

**Comment by kubitron** [comment]
Latest commit on my master branch should make editing and deleting keys much more intuitive.  Give it a try.

https://github.com/kubitron/redmine_git_hosting/
