### ISSUE TITLE
View not updating

### ISSUE THREAD

**Issue by incorvia** [ericpaulbishop/redmine_git_hosting#139]
I feel I've done everything correctly though there must be one thing a-miss.. I've installed everything and I can push and pull repositories through gitolite fine.. when I create repositories and delete projects via the front-end, I can see that repositories are created and destroyed.  I also (believe) I have my user's public key in ChiliProject correctly.  The only thing that doesn't seem to happen is my 'repositories' view always stays on the configuration screen telling you how to configure a new repository, even though I've already made a test commit.....  It still says:

Repository is empty. Get started by following the instructions below.

Help is appreciated...

**Comment by kubitron** [comment]
If you were able to create a test commit using the user's key, then all should be well in that respect.  This problem sounds more like the notification is not working properly..

Try executing a "fetch_changesets" operation and see if this fixes things.

This version of the plugin has the ability to get confused and stuck under a variety of circumstances.  I would suggest trying my version @ https://github.com/kubitron/redmine_git_hosting/.  Among other things, it is possible that the notification hook key is improperly installed and thus notification of updates is not getting to Redmine.  Hope this helps.

**Comment by incorvia** [comment]
@kubitron I ran a fetch from the app root with:

ruby script/runner "Repository.fetch_changesets" -e production

But no avail.. I'll try your version and post back here.

**Comment by incorvia** [comment]
Hmm.. still stuck.. I deleted the vendors/plugins/redmine_git_hosting.. then went through the steps again.. but with your plugin (though I left the db as is).. and then restarted the server.. I should note that passenger fails to load chiliproject unless I delete a few colons at the end of if lines in the plugin.. this was the same case with the original plugin.. I'm a relatively new so I had never seen that syntax before, and don't really understand its need.. once deleted the app fires up.. I deleted all current repositories / projects and tried again.. i can still push pull and everything but the view doesn't update :-|

**Comment by incorvia** [comment]
@kubitron I should note.. one thing that stopped working when I switched to yours was that the gitolite.conf stopped updating... so I was losing permission to push and pull.. I downgraded and this was immediately fixed with no other alterations.. just a heads up.

**Comment by kubitron** [comment]
Um.... Which version did you download?  Did it say what was wrong in the log?  In general, my version fixes those problems that are common in the previous version of the plugin.  Do you have the log messages when it stopped updating? (They should be clearly shown with a "***>" .

Also, did you remember to do a "rake db:migrate_plugins RAILS_ENV=production" before trying to run it?

**Comment by kubitron** [comment]
Send me email, perhaps I can help..

**Comment by incorvia** [comment]
@kubitron Hey, thanks for the help and offer to help further.. I actually kind of got tired of the whole thing.  So I went with Redmine instead, a clean and stable version (1.3) on a fresh database (mysql).. and used your plugin with that.. and everything worked great.  So for now, anyways I don't know if it was the database, or ChiliProject or what, but I'm happy, so thank you, thank you.. and I'll close this :)

**Comment by kubitron** [comment]
Glad to hear that you got things working.  It may be a problem with ChiliProject (I don't run ChiliProject).

At any rate, if you have _any_ problems with my plugin, post issues on my redmine_git_hosting page -- I'll see what I can do.

**Comment by incorvia** [comment]
Will do, thanks!
