### ISSUE TITLE
Why not use #{RAILS_ROOT}/tmp for temporary directory ?

### ISSUE THREAD

**Issue by ech1965** [ericpaulbishop/redmine_git_hosting#14]
Hello,

I've managed to deploy chiliproject 1.3 + gitolite + redmine_git_hosting on a dreamhost account ( using one shell account for the chiliproject site and one shell account reserved for subversion and git hosting).

I had an issue with the plugin trying to create a directory in /tmp.... As dreamhost is a kind of shared hosting... I do not want to write in a global /tmp.

As a quick hack,  I've added a line in the config/environment.rb to overrride the ENV['TMPDIR'] variable and use $HOME/tmp.

Is there any reason for using Dir.tmpdir instead of creating a directory in #{RAILS_ROOT}/tmp ?

Thanks for your useful plugin !!

**Comment by ericpaulbishop** [comment]
This really isn't meant for shared hosting.  The latest version of the plugin requres the configuration of sudo, which you're not going to be able to do on shared hosting -- you'll need a VPS node or other fully-configurable server.  If you do have a dedicated server (which is more-or-less required in the newer version of the plugin which uses sudo) using /tmp seems the right strategy.  I'm therefore closing this issue.

You may want to consider forking the old ssh branch and developing that independently to suit your needs.
