### ISSUE TITLE
getting 404 when using Smart HTTP

### ISSUE THREAD

**Issue by levelos** [ericpaulbishop/redmine_git_hosting#140]
Production log entry:

```
Processing GitHttpController#index (for 96.25.93.249 at 2012-01-20 17:26:35) [GET]
 Parameters: {"controller"=>"git_http", "id"=>"test1", "path"=>"test1.git", "p3"=>"", "action"=>"index", "p2"=>"", "p1"=>""}
Completed in 7ms (View: 0, DB: 1) | 404 Not Found [http://example.com/test1.git]
```

I have smarthttp enabled for both http and https (just for testing). Thanks!

**Comment by kubitron** [comment]
Um.... Make sure you are using the right syntax for you pull, for instance for a top-level repo:

git clone http://your.server.name.com/reponame.git

Also, you might try my version of the plugin and see if it works better (I rewrote a bunch of the path code):

https://github.com/kubitron/redmine_git_hosting

**Comment by levelos** [comment]
Thanks John - I actually got things working. I was falsely assuming I could browse the repo in a browser via http. Checkout's, etc. work fine. I just got things working well on the Eric's master branch. Any major reasons to switch to yours? Thanks!
