### ISSUE TITLE
Sub-projects show/use the wrong path for the repo

### ISSUE THREAD

**Issue by that0n3guy** [ericpaulbishop/redmine_git_hosting#16]
I created a project called "test".  Then a subproject under it called "subtest".

The url shows as <code>git@git.mysite.com:test/subtest.git</code>

The instructions show:
The instructions show:     Repository Setup:

```
    mkdir subtest
    cd subtest
    git init
    touch readme.txt
    git add readme.txt
    git commit -m 'Initializing Test repository'
    git remote add origin git@git.mysite.com:test/subtest.git
    git push origin master

Existing Git Repo?

    cd existing_git_repo
    git remote add origin git@git.mysite.com:test/subtest.git
    git push origin master
```

This doesn't work though.  To get my repo to work and to show in the repo-viewer (in chiliproject) I had to use <code>git@git.git@git.mysite.com:subtest.git</code> (notice not a subdirectory of "text")

So the text and URL needs fixed or the plugin needs to create the text/subtest.git repo instead of just the ./subtest.git repo (probably just fix the url or text would be fine since all project names need to be unique anyways).

**Comment by that0n3guy** [comment]
Oh dang... I just saw: https://github.com/ericpaulbishop/redmine_git_hosting/commit/d1dafc90e9eb22a19cb079b5a3420a8f9e602aba

Let me test that.

**Comment by that0n3guy** [comment]
I just checked, I am running the latest already.  Things are still messed up.

**Comment by that0n3guy** [comment]
I believe this bug goes along with #12, see my comment here: 

https://github.com/ericpaulbishop/redmine_git_hosting/issues/12#issuecomment-1319375

**Comment by ericpaulbishop** [comment]
This issue should be fixed now -- please try with latest update
