### ISSUE TITLE
gl-setup - command not found on plugin related migrations

### ISSUE THREAD

**Issue by ruigoncalves** [ericpaulbishop/redmine_git_hosting#169]
Hi there!

When I runned the command sudo RAILS_ENV=production rake db:migrate_plugins to apply the needed migrations for the plugin, the following message was outputted:
_bash: gl-setup: command not found_

What could be wrong with my gitolite setup?

Thanks in advance for the help,
Regards!

**Comment by MichaelKling** [comment]
gitolite 3.x doesnt has this commands anymore.  you have to downgrade gitolite or update the redmine_git_hosting plugin in order to use the new commands.  (like with git all gitolite start now with gitolite <comanndname> - in this case "gitolite setup")

**Comment by ruigoncalves** [comment]
I'm using the plugin version 0.4.2. Do know if this version its the latest one?

**Comment by MichaelKling** [comment]
there are various forks, some put different version numbers etc, but i dont know any fork for gitolite 3

**Comment by ruigoncalves** [comment]
I decided to reinstall again the gitolite previous version and everything went fine.
