### ISSUE TITLE
Empty git repository URL

### ISSUE THREAD

**Issue by krlsBC** [ericpaulbishop/redmine_git_hosting#178]
Hi! 

I´m working with Redmine 1.3.3 and this plugin, everything works flawlessly.

I can manage SSH keys, create repositories, push to the server and download on other machine.

But I can only see the repository URL when this is empty, on the instructions.

This is on project overview:

![image](https://f.cloud.github.com/assets/3245972/126928/0eeb7576-6f7b-11e2-9370-17ce1eb702a5.png)

And this on repository tab:

![image](https://f.cloud.github.com/assets/3245972/126932/3d91945a-6f7b-11e2-9513-62f697062d99.png)

I´m using the following versions:

ruby 1.8.7
rails 2.3.14

**\* LOCAL GEMS ***

actionmailer (2.3.14)
actionpack (2.3.14)
activerecord (2.3.14)
activeresource (2.3.14)
activesupport (2.3.14)
bundle (0.0.1)
bundler (1.2.3)
domain_name (0.5.7)
i18n (0.4.2)
inifile (2.0.2)
json (1.7.6)
lockfile (2.1.0)
mechanize (2.5.1)
mime-types (1.20.1)
multipart-post (1.1.5)
mysql (2.9.0)
net-http-digest_auth (1.2.1)
net-http-persistent (2.8)
net-ssh (2.6.3)
nokogiri (1.5.6)
ntlm-http (0.1.1)
oauth (0.4.7)
rack (1.1.5)
rails (2.3.14)
rake (10.0.3)
rdoc (3.12)
rmagick (2.13.1)
shoulda (2.11.3)
unf (0.0.5)
unf_ext (0.0.5)
webrobots (0.0.13)

Any idea?

**Comment by mercury00** [comment]
I don't have any ideas, but thought I'd at least warn you that rails 2.3.14 has a critical security vulnerability known publicly.  I'd recommend updating rails to 2.3.15, to avoid being hacked.

**Comment by krlsBC** [comment]
Thanks mercury00 for the advise!

I´ll try to see if 1.3.3 redmine works fine with 2.3.15.

**Comment by krlsBC** [comment]
Changing this file:

redmine_git_hosting / app / views / projects / _git_urls.erb

By adding this code:

<% git_ssh_url = Setting.plugin_redmine_git_hosting['gitUser'] + "@" + Setting.plugin_redmine_git_hosting['gitServer'] + ":" + GitHosting.repository_name(@project) + '.git'  %>

<%= git_ssh_url %>

I´m able to see the URL on plain text. 

Just what I need.
