### ISSUE TITLE
Repository page not updating

### ISSUE THREAD

**Issue by micah** [ericpaulbishop/redmine_git_hosting#183]
I created a new project, and a new repository. The repository seems created fine and I can push to it, but the repository viewer doesn't seem to be updating. When I view it, I see this in the log:

```
2014-03-18 10:20:40 -0700 ERROR [GitCache] repo_id is nil, exit!
```

I'm using the latest version of the devel branch, with redmine 2.4.2 and git 1.8.5.3. I tried to also run the rake task to update the changesets, but that didn't seem to help. I tried disabling the cache to see if that would work, but no dice.

Let me know if there is any additional information I can provide or tests I can make!

**Comment by n-rodriguez** [comment]
@micah  This is not the good repository, here's the one : https://github.com/jbox-web/redmine_git_hosting

**Comment by micah** [comment]
thanks!
