### ISSUE TITLE
SSH git repository link on Overview and Repository pages has wrong default value if all HTTP/HTTPS access is disabled

### ISSUE THREAD

**Issue by lostar** [ericpaulbishop/redmine_git_hosting#2]
How to reproduce:
1. Open Project -> Settings -> Repository page. Change "Git Daemon" and "Git Smart HTTP" to disabled state. Save.
2. Open Project -> Overview or Project -> Repository page. URL field for SSH access will have empty value.

Workaround:
If manually click on SSH button then right URL will be displayed.

**Comment by ericpaulbishop** [comment]
should be fixed now

**Comment by lostar** [comment]
thx. It works!
