### ISSUE TITLE
Deleting repository on redmine does not delete actual repository

### ISSUE THREAD

**Issue by s0undt3ch** [ericpaulbishop/redmine_git_hosting#22]
Deleting repository on redmine does not delete actual repository.

The delete repository setting is set to enabled.

**Comment by ericpaulbishop** [comment]
I just tested with Redmine 1.2.0 and the latest version of the plugin and could not reproduce the problem.  I am therefore closing this issue.  If you continue to have problems and can give more detailed instructions on how to reproduce the problem feel free to re-open the issue.
