### ISSUE TITLE
Git repo isn't moved when a project becomes a subproject & duplicates

### ISSUE THREAD

**Issue by that0n3guy** [ericpaulbishop/redmine_git_hosting#23]
There are several problems here I think:
- First, when a project is moved into a subproject, the repo not moved but a new empty repo is created.  
- Second.  The repository url (http://yoursite.com/projects/myproject/repository) shows commits to the old repo, not the new one.

How to duplicate this issue:
- Create "test" project with repo
- create "myproject" project with repo
- push git commits to "myproject"
- go to url http://yoursite.com/projects/myproject/repository .. you will see your commit and see a url of git://yoursite.com:myproject
- in the settings, set "myproject" a subproject of "test"
- now go to http://yoursite.com/projects/myproject/repository ... it looks the same (you still see the commit) but the url now says git://yoursite:test/myproject

From here you now have 2 repos for "myproject".  One located at ~/repositories/myproject.git and one at ~/repositories/test/myproject.git.  The one at test/myproject.git is empty.  The other isn't.

Also, if you try to use the NEW git url for cloning and pushing.  Your changes won't show up on the http://yoursite.com/projects/myproject/repository page, since it still references the old git repo.

**Comment by ericpaulbishop** [comment]
This should now be fixed.
