### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by lspg** [ericpaulbishop/redmine_git_hosting#24]
Hi,

i used perfectly redmine-gitosis by xdissent for some times, but now i just moved to gitolite i'd like to try your plugin.
To that purpose i upgraded redmine to 1.2 stable and it does work well.
I couldn't find any documentation how to install nor configurate your plugin, so i just installed it the usual redmine way.
But i got a blank screen when i restart my web server (apache+passenger) and try to load redmine. Redmine's log gives me ""404 Not found".

Any advice please ? or a link ?

**Comment by ericpaulbishop** [comment]
This is rather vague, and I haven't been able to reproduce the error, so I'm going to close the issue.
