### ISSUE TITLE
Cant find the problem (gitolite/redmine both work fine)

### ISSUE THREAD

**Issue by zetsub0u** [ericpaulbishop/redmine_git_hosting#25]
Hi,

I have both gitolite and redmine working just fine, i can create repos and access with the keys i put on gitolite fine and redmine works awesome, i installed the plugin, configured it on the plugin page, put the keys in place, one that can commit to gitolite-admin repo and one that has shell access as the git user. But when i create a project on redmine nothing happens, i see no log anywhere, no error anywhere, messages log dont have any ssh attempt, redmine and nginx logs have nothing related, same with adding a key to a user, it's getting added on the database, but nothing happens with gitolite.

I've been banging my head for 2 days, it's probably something stupid but i can't think of any other possible problem.
Any help?

Thanks

**Comment by perryk** [comment]
Just a random guess, check the permissions on the ssh keys. If they have any group or other permissions set they likely will not work. i.e chmod 600 them.

Set your logging level to DEBUG in config/environments/<instance>.rb (likely production.rb) with this line:
config.logger.level = Logger::DEBUG

You can check apache logs also.

What process is your redmine running as ? It is likely to be the owner of the application files.

As that user you can try running the following command:
/tmp/redmine_git_hosting/run_git_as_git_user --version

This should return the version of git but be run via ssh as your git user.

There is a step during the install which you want to add the git_user_id_rsa.pub key to gitolite's authorized keys file. Have you done that ?

As someone else here suggested, try following lines 25 through 123 on this: https://github.com/ericpaulbishop/yourchili/blob/master/library/git.sh

It gives a pretty good example on what to do for an install.

**Comment by zetsub0u** [comment]
Hi, thanks for answering, yes the permissions are all correct, i can su - to the user that nginx runs on (redmine) which owns the redmine files and the ssh keys and i can do an ssh with these keys just fine, so it's not a permission problem. I can also run these /tmp files fine and there's nothing on nginx logs, i'm going to try turning on debug now and see if i spot something.

**Comment by zetsub0u** [comment]
Ok, apparently there is some problem with the /tmp scripts and /usr/local/bin/gl-auth-command

Tried running the command by hand:
ssh -o BatchMode=yes -o StrictHostKeyChecking=no -i /opt/redmine/.ssh/git_user_id_rsa git@localhost "git --version"

And i just get a "bad command: git --version", i',m thinking this is a problem with gitolite, but if anyone knows what could be going wrong, that would be cool.

Thanks.

**Comment by zetsub0u** [comment]
export SSH_ORIGINAL_COMMAND="git --version"; /usr/local/bin/gl-auth-command user
This should replicate the ssh, and i still get the bad command, is that right?

Also, i enabled debug loging and all i see is this: Shelling out: '/tmp/redmine_git_hosting/run_git_as_git_user' --version --no-color

No errors.

**Comment by zetsub0u** [comment]
So after battling it out for a day, did some debugging of the ruby and found out my problem was that phusion passenger wasnt running with the same user nginx was, which is the user that could access the keys and all that and was using nobody instead, fixed that and it seems to be coming to life.

Now i cant seem to be able to get the repository to show on redmine, its creating the repo and updating the keys and all that, but it says:

fatal: Not a git repository: 'repositories/test3.git'

on my error.log, when it is a repo and i can checkouot and push stuff there from other machines. This worked before installing the plugin with normal non-gitolite repos.

Any clues?

**Comment by zetsub0u** [comment]
https://github.com/ericpaulbishop/redmine_git_hosting/issues/15 Had the answer.

After 3 painstakingly long days at work i got this up and running, now to migrate those big svn/trac projects and see what happens.
