### ISSUE TITLE
Required Permissions check not working

### ISSUE THREAD

**Issue by deflomu** [ericpaulbishop/redmine_git_hosting#39]
Hey,

on my server (Debian Squeeze, chiliproject trunk, redmine_git_hosting trunk) the sudo checks were not working. It saved: "-sh: echo -n: not found"

Changing the sudo test command from 'sudo ... -i "echo -n" 2>...' to 'sudo ... -i echo -n 2>...' in lib/git_hosting.rb fixed the problem.

**Comment by ericpaulbishop** [comment]
Should be fixed now
