### ISSUE TITLE
SSH on non-standard address

### ISSUE THREAD

**Issue by TheEmpty** [ericpaulbishop/redmine_git_hosting#4]
Tried both: localhost -p 2000 and localhost:2000
With a port the git URLs change to, ex: `git@site:repo.git` becomes `ssh://git@site:socket/repo.git`

**Comment by kalle** [comment]
I have implemented this myself as a setting in the GUI. Take a look at:
https://github.com/ericpaulbishop/redmine_git_hosting/pull/13

**Comment by ericpaulbishop** [comment]
This feature is somewhat esoteric and I am somewhat skeptical how useful it will be for most people.  I'm therefore not going to include it -- feel free to pull from kalle's branch if you need it.

**Comment by TheEmpty** [comment]
That's sad, I do suggest you look into SSH security. The big first steps
are: Make it via Key Auth, then move it off the default port. A lot of bots
will mass SSH attempts from different IPs, etc.

On Mon, Jul 11, 2011 at 2:31 PM, ericpaulbishop <
reply@reply.github.com>wrote:

> This feature is somewhat esoteric and I am somewhat skeptical how useful it
> will be for most people.  I'm therefore not going to include it -- feel free
> to pull from kalle's branch if you need it.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/ericpaulbishop/redmine_git_hosting/issues/4#issuecomment-1548701

## 

محمد Τυπάλδος
This E-Mail address is FaceTime and iMessage enabled

**Comment by ericpaulbishop** [comment]
Gitolite is setup to use public key auth only.  It's quite secure,
even on the default port.

On Mon, Jul 11, 2011 at 2:33 PM, TheEmpty
reply@reply.github.com
wrote:

> That's sad, I do suggest you look into SSH security. The big first steps
> are: Make it via Key Auth, then move it off the default port. A lot of bots
> will mass SSH attempts from different IPs, etc.
> 
> On Mon, Jul 11, 2011 at 2:31 PM, ericpaulbishop <

**Comment by marfarma** [comment]
My server is already in use and configured to ssh through a non-standard port.

I'm happy to have the opportunity to pull from kalle's branch -- but I'd like it if you reconsider pulling the fix.

Or, at least, adding this issue and then mention kalle's branch as an option to work around it in the footnotes on the installation directions.
