### ISSUE TITLE
typo in git caching patch?

### ISSUE THREAD

**Issue by ohthehugemanatee** [ericpaulbishop/redmine_git_hosting#42]
Caught this error in logs while working today:  ActiveRecord::StatementInvalid (Mysql::Error: Unknown column 'created_on' in 'order clause': SELECT \* FROM `git_caches`  ORDER BY created_on ASC LIMIT 1):

This looks like it's just a simple typo in vendor/plugins/redmine_git_hosting/lib/git_hosting/patches/git_adapter_patch.rb , trying to sort by "created_on", which doesn't exist.  Everything works if I use created_at instead.

**Comment by ericpaulbishop** [comment]
Should be fixed now, thanks for pointing this out
