### ISSUE TITLE
ActiveRecord::SerializationTypeMismatch when displaying Actifity tab

### ISSUE THREAD

**Issue by deflomu** [ericpaulbishop/redmine_git_hosting#46]
Hey,

I'm getting a 500 Internal Server error when displaying the activity tab. The log says:

ActiveRecord::SerializationTypeMismatch (changes was supposed to be a Hash, but was a String):  
  app/models/journal.rb:103:in `method_missing'                                                                         
  lib/redmine/activity/fetcher.rb:86:in`events'  
  lib/redmine/activity/fetcher.rb:86:in `sort!'                                                                         
  lib/redmine/activity/fetcher.rb:86:in`events'  
  app/controllers/activities_controller.rb:37:in `index'  
  public/dispatch.fcgi:24

I'm on the latest chiliproject master and on the latest master of redmine_git_hosting. Database is mysql and git caching is enabled (1000 items and 10mb, also no idea what are reasonable values).

I'm happy to give more informations as needed, but I have no idea what is needed :) I have also no idea if this is an issue of this plugin or chiliproject.

**Comment by ericpaulbishop** [comment]
That looks like an issue with how you have redmine configured, not the plugin.  Your description has no information that leads me to suspect anything is going wrong with the plugin.  Make sure you have redmine running properly, THEN install the plugin.

**Comment by deflomu** [comment]
Just for the record: It was no issue of the plugin nor of chiliproject. I messed up the Journals table and fixed it by deleting its contents.
