### ISSUE TITLE
branching support in fetch_changesets

### ISSUE THREAD

**Issue by ohthehugemanatee** [ericpaulbishop/redmine_git_hosting#48]
I've noticed that Repository.fetch_changesets_for_project() only seems to pull in changesets for the master branch.  I guess it's just the difference between running "git log" and "git log --all"?  Or maybe "git push --all" in a post-commit hook somewhere.

**Comment by ericpaulbishop** [comment]
The relevant method being called is in core Redmine/ChilliProject code.  This isn't a bug with the plugin.
