### ISSUE TITLE
Gitolite Server Domain

### ISSUE THREAD

**Issue by TheEmpty** [ericpaulbishop/redmine_git_hosting#5]
Gitolite Server Domain should be a separate entry from: Gitolite Public Server Domain (where users connect, what is displayed, etc)

Many hosting services (Amazon EC2, etc) will charge you for bandwidth for pulling from yourself that way and ask you to use either localhost your machines local-ip.

**Comment by ericpaulbishop** [comment]
Now that we're running git though sudo instead of ssh (since it's much faster), this is no longer an issue.
