### ISSUE TITLE
in `build': You have a nil object when you didn't expect it! 

### ISSUE THREAD

**Issue by voondo** [ericpaulbishop/redmine_git_hosting#54]
Hi,

I have this error :

<pre>
=> Booting WEBrick
=> Rails 2.3.11 application starting on http://0.0.0.0:3000
/usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/routing/builder.rb:159:in `build': You have a nil object when you didn't expect it! (NoMethodError)
You might have expected an instance of ActiveRecord::Base.
The error occurred while evaluating nil.[]
        from /usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/routing/route_set.rb:310:in `add_route'
        from /usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/routing/route_set.rb:19:in `connect'
        from /var/lib/redmine/vendor/plugins/redmine_git_hosting/lib/git_hosting.rb:92:in `add_route_for_project_with_map'
        from /var/lib/redmine/vendor/plugins/redmine_git_hosting/lib/git_hosting.rb:84:in `add_route_for_project'
        from /usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/routing/route_set.rb:227:in `draw'
        from /var/lib/redmine/vendor/plugins/redmine_git_hosting/lib/git_hosting.rb:83:in `add_route_for_project'
        from /var/lib/redmine/vendor/plugins/redmine_git_hosting/config/routes.rb:3
        from /var/lib/redmine/vendor/plugins/redmine_git_hosting/config/routes.rb:2:in `each'
        from /var/lib/redmine/vendor/plugins/redmine_git_hosting/config/routes.rb:2
        from /usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:171:in `load_without_new_constant_marking'
        from /usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:171:in `load'
        from /usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:547:in `new_constants_in'
        from /usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:171:in `load'
        from /usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/routing/route_set.rb:287:in `load_routes!'
        from /usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/routing/route_set.rb:287:in `each'
        from /usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/routing/route_set.rb:287:in `load_routes!'
        from /usr/lib64/ruby/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/routing/route_set.rb:267:in `reload!'
        from /usr/lib64/ruby/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:537:in `initialize_routing'
        from /usr/lib64/ruby/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:188:in `process'
        from /usr/lib64/ruby/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:113:in `send'
        from /usr/lib64/ruby/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:113:in `run'
        from /var/lib/redmine/config/environment.rb:20
        from /usr/lib64/ruby/site_ruby/1.8/rubygems/custom_require.rb:54:in `gem_original_require'
        from /usr/lib64/ruby/site_ruby/1.8/rubygems/custom_require.rb:54:in `require'
        from /usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in `require'
        from /usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:547:in `new_constants_in'
        from /usr/lib64/ruby/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in `require'
        from /usr/lib64/ruby/gems/1.8/gems/rails-2.3.11/lib/commands/server.rb:84
        from /usr/lib64/ruby/site_ruby/1.8/rubygems/custom_require.rb:54:in `gem_original_require'
        from /usr/lib64/ruby/site_ruby/1.8/rubygems/custom_require.rb:54:in `require'
        from script/server:3
</pre>

What's wrong ?

**Comment by ericpaulbishop** [comment]
I believe the source of this error is fixed in the latest version of the plugin (v0.4.0).
