### ISSUE TITLE
Git Repository Urls shown on project overview even when repository module is disabled

### ISSUE THREAD

**Issue by amotools** [ericpaulbishop/redmine_git_hosting#55]
We have many projects where we don't need any repository. So the repository module is disabled in project configuration. After  installing the plugin on every project overview page the "Git Repository" block is shown even if the module is enabled or not.

I think when the module "Repositories" is disabled for a project, no output should be made by this plugin. 
Do you think also?

Best Regards
Renzo

**Comment by amotools** [comment]
I have corrected this with an additional if in views/projects/_git_urls.erb like this:

<pre>
&lt;% if (!User.current.anonymous?) || project.repository[:git_http].to_s != "0" || (project.is_public && project.repository[:git_daemon].to_s != "0" ) %&gt;
&lt;% if (project.module_enabled?(:repository)) %&gt;  &lt;!-- NEW if for checking if repository module is enabled --&gt;
<div class="box">
        &lt;h3>Git Repository&lt;/h3>
        &lt;div id="git_url_box">
...
&lt;% end %&gt; &lt;!-- NEW end correspondig to if --&gt;
</pre>

**Comment by s0undt3ch** [comment]
It should be an "AND" for all those "OR"'s, not another if.

**Comment by s0undt3ch** [comment]
Actually I can't confirm this on my Chiliproject 2.1.1 test instance.

**Comment by s0undt3ch** [comment]
This commit https://github.com/s0undt3ch/redmine_git_hosting/commit/cf6bbf7e619b52d911eac17e7b66a0b88d24d11b fixes your issue, although it only happens if a repository exists, ie, you created the repository and afterwards disabled that module.
