### ISSUE TITLE
Key file disappears and cannot be readded

### ISSUE THREAD

**Issue by ghost** [ericpaulbishop/redmine_git_hosting#57]
Thanks a million for this plugin - It's fantastic.  I've noticed that when I "delete" a key, it is deactivated, but remains in the database.  If I go to re-add that key in the future, it just fails silently and never adds the key.  I guess the expected behavior would be that the key is deleted entirely (and could be added again later).  Alternatively, if the key needs to be kept in the database, it would be nice if there was a way to re-enable it from the interface.

**Comment by csherrell** [comment]
I see this ticket is closed, but what was the outcome?  I have the same issue and question.

Seems like if you were able to delete a key, then you would be able to add it back, and if you deactivated a key, then there should be some kind of list that would let you reactive it.  Right now, delete and un-checking the active box do the same thing, both resulting in not allowing a previously used key identifier to be used again.
