### ISSUE TITLE
Support Redmine's "Report last commit for files and directories" option

### ISSUE THREAD

**Issue by ghost** [ericpaulbishop/redmine_git_hosting#59]
I noticed when using this plugin that when I made a  repository, Redmine's "Report last commit for files and directories" option isn't shown in the repository tab for the settings, and the effects of it are disabled in the repository tab. Seeing with all the new caching and whatnot, how about putting that option back in and enabling it by default? :) This goes perfectly with the new hook system you guys are working on. Can't wait for it!

**Comment by ericpaulbishop** [comment]
I just added a patch to address this -- it doesn't add a setting for this, but it sets this parameter to always be true. Try it again now.
