### ISSUE TITLE
Still Less Invasive Models

### ISSUE THREAD

**Issue by s0undt3ch** [ericpaulbishop/redmine_git_hosting#62]
Glad to see you've merged my work into your `new_hook_handling`. I can now start deleting my feature branches.

Regarding the "less invasive models", you did what I was going to do with the CIA notifications stuff, ie, stick that into extra.
Yet, regarding the CIA notifications, we're still invasive in the changeset's table, ie, in order to not repeat notifications, for example, when branches are merged, I created a `cia_notified` column.

How do you think we should handle that, create a notifications table, related to changeset's, to store that "bit"?

**Comment by s0undt3ch** [comment]
Should we add another column to the extra's table which will store an array of the notified commits?

**Comment by ericpaulbishop** [comment]
That sounds like a good strategy. If you implement it, I'll merge it in.

Eric

On Mon, Aug 15, 2011 at 11:10 AM, s0undt3ch
reply@reply.github.com
wrote:

**Comment by ericpaulbishop** [comment]
By the way -- I just looked at your latest commit to move the CIA
stuff into the extras table.  Storing the changeset ids in an array is
a bad idea.

I think it would probably be better to have a new table for this, and
most importantly: index the changeset id column.  You want to be able
to do an efficient lookup of the changeset id and whether a
notification has been sent for it, not iterate through an array.  It's
the difference between O(1) and O(n).

Eric

**Comment by s0undt3ch** [comment]
Ok, I'll do that, ie, that extra table.

**Comment by s0undt3ch** [comment]
By the way, `column_exists?` was introduced in rails 3.0 right? At least if failed on my end.

**Comment by ericpaulbishop** [comment]
You may be right.. I need to do a lot more testing, I'm getting some
errors when I try to install the merged version right now (though this
is exactly why I have it in a separate branch).  I've been
ridiculously busy with other things lately, so work on this has been
slow.

Eric

On Mon, Aug 15, 2011 at 5:21 PM, s0undt3ch
reply@reply.github.com
wrote:

**Comment by s0undt3ch** [comment]
One more thing, the update you've made, `Repository.send(:accepts_nested_attributes_for, :extra, :allow_destroy =>true, :update_only => true)` makes functionality break, you can no longer save the repository settings, that's why I wasn't doin' it.

On `activerecord-2.3.12/lib/active_record/nested_attributes.rb`, line 282, `check_existing_record = (options[:update_only] || !attributes['id'].blank?)` options are `nil` that's what's failing. Note that "under" the repositories_controller patch, `@project.repository.nested_attributes_options` is not nil.

Haven't found a fix for that yet, can you?

**Comment by ericpaulbishop** [comment]
I know it's broken... but your way didn't work either.  If you have a
patch that works send it to me.

Eric

On Wed, Aug 17, 2011 at 8:31 AM, s0undt3ch
reply@reply.github.com
wrote:

**Comment by s0undt3ch** [comment]
I was able to save the settings properly, I tried it. hmmm....

**Comment by ericpaulbishop** [comment]
It's true that with your way, saving doesn't actually crash/produce an
error.  However, itdoesn't save the value(s), which is just as bad.

On Wed, Aug 17, 2011 at 8:57 AM, s0undt3ch
reply@reply.github.com
wrote:

**Comment by s0undt3ch** [comment]
I'll try my way again, I could swear that the values were saved.

**Comment by s0undt3ch** [comment]
Ok, if you reload the page, the new settings are there, though, what got saved won't show up until you reload, looking at it. This did not happen before.

**Comment by s0undt3ch** [comment]
And, this also did not happen before, it only get's properly saved if done after calling `edit_without_scm_settings` which explains why the page needs a reload.

**Comment by s0undt3ch** [comment]
Ok, the changes made to my post-receive-hook is now working and it includes cia notifications in it's own table.
Repository settings save is working.

**Comment by s0undt3ch** [comment]
Updated my branch to manual push mirrors...

**Comment by ericpaulbishop** [comment]
This is now merged into master
