### ISSUE TITLE
Add hint to README when running apache with mod_fcgid

### ISSUE THREAD

**Issue by deflomu** [ericpaulbishop/redmine_git_hosting#64]
To enable http repositories with apache and mod_fcgid you need to put "Passheader Authorization" into the virtualhost section of the apache config. Otherwise you will get "fatal: Authentication failed" when trying to access a repo via https.

This is not exactly a Issue but I wanted to write somewhere down, so other people can find it.

**Comment by ericpaulbishop** [comment]
Done
