### ISSUE TITLE
Need to recreate scripts in `/tmp/redmine_git_hosting` after settings change

### ISSUE THREAD

**Issue by DarwinAwardWinner** [ericpaulbishop/redmine_git_hosting#66]
When one changes the git user setting, and possibly others, the script files in `/tmp/redmine_git_hosting` need to be updated with the new configuration values. Right now, they retain the old values until manually deleted, which means that some configuration options seem to have no effect, which makes setup difficult.

**Comment by rehmsen** [comment]
I was experiencing the same problem when updating from an older version of the plugin. The scripts would still contain the ssh stuff. Should this not be updated upon migrate-plugins?

**Comment by ericpaulbishop** [comment]
I've now added some code to do this automatically where appropriate.  Please try again with v0.4.0
