### ISSUE TITLE
/tmp/redmine_git_hosting crashed

### ISSUE THREAD

**Issue by gartz** [ericpaulbishop/redmine_git_hosting#69]
I you somehow stop the process in the middle when updating the temporary gitolite-admin folder created in the /tmp/ from the plugin, the gitolite-admin repositore can crash somehow.

Then aways when someone change something, before it push the commit to the server, it drops an error and stop the process.

So the simple solution is to purge the folder, then the plugin will clone again before made the commits changes and push again.

I think for a stability solution, was nice if the response from the remote gitolite-admin was not successful for any reason, purge the folder then try again, if don' t fix, throw an error for the redmine administrator fix it.

**Comment by ericpaulbishop** [comment]
There is a huge performance penalty to re-cloning every time.  Doing it that way is massively inefficient.

The question is, why are you seeing a crash?  What errors are you getting?  The only information you've provided is that something went wrong when pushing changes to gitolite-admin.  The best way to deal with that is to figure out what, specifically went wrong and fix it.

**Comment by gartz** [comment]
Sorry, my mistake. I have this problem in the last week and don't have the trace to put here anymore... But, it happens twice already.
So when it happens again I will publish the trace together and the git push error too.

I remember its something with the tree hash been different from the bare server.

And my suggestion will not clone the repo all times, just when it can't, for any reason, push the last commits for the gitolite-admin.

**Comment by ericpaulbishop** [comment]
I haven't heard back from you on this issue recently.  Since, from what you say and based on the timing, I think you were running 0.3.0 at time you had these issues.

I'm going to close this issue for now, until you can (1) Confirm this is happening on 0.4.1 or (2) provide more details on the errors/logs you're seeing.  If/when you encounter a similar error, feel free to re-open or file another report.

**Comment by gartz** [comment]
I have updated to the last version. The problem has been fixed. Thank you.
