### ISSUE TITLE
repository not created for project

### ISSUE THREAD

**Issue by czechbox** [ericpaulbishop/redmine_git_hosting#72]
I've gotten most of this to work, but this portion. When I create a new repo for a project, it fails to add it to the gitolite.conf so I have to manually add it in my local gitolite.conf file (after which it's fine). Here's the error I'm getting:

Processing RepositoriesController#edit (for 202.37.225.46 at 2011-09-06 03:12:34) [POST]
  Parameters: {"commit"=>"Create", "action"=>"edit", "authenticity_token"=>"tfnP1Wh7Ie793P5sGo30xwLE1KTdVfOUnW0JRVTlWpw=", "id"=>"altlayout", "controller"=>"repositories", "extra"=>{"git_http"=>"0", "git_daemon"=>"0", "notify_cia"=>"0"}, "repository_scm"=>"Git"}
Cloning gitolite-admin repository
Creating MD5 digests for Redmine Git Hosting hook
Digest for post-receive.redmine_gitolite.rb: b007f793382102ff9f0f2a54b5a057c8
Our hook is already installed

Errno::ENOENT (No such file or directory - /tmp/redmine_git_hosting/gitolite-admin/conf/gitolite.conf):
  passenger (3.0.8) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
  passenger (3.0.8) lib/phusion_passenger/abstract_request_handler.rb:513:in`accept_and_process_next_request'
  passenger (3.0.8) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
  passenger (3.0.8) lib/phusion_passenger/classic_rails/application_spawner.rb:321:in`start_request_handler'
  passenger (3.0.8) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `send'
  passenger (3.0.8) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in`handle_spawn_application'
  passenger (3.0.8) lib/phusion_passenger/utils.rb:479:in `safe_fork'
  passenger (3.0.8) lib/phusion_passenger/classic_rails/application_spawner.rb:270:in`handle_spawn_application'
  passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
  passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:357:in`server_main_loop'
  passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:180:in`start'
  passenger (3.0.8) lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
  passenger (3.0.8) lib/phusion_passenger/spawn_manager.rb:219:in`spawn_rails_application'
  passenger (3.0.8) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
  passenger (3.0.8) lib/phusion_passenger/spawn_manager.rb:214:in`spawn_rails_application'
  passenger (3.0.8) lib/phusion_passenger/abstract_server_collection.rb:82:in `synchronize'
  passenger (3.0.8) lib/phusion_passenger/abstract_server_collection.rb:79:in`synchronize'
  passenger (3.0.8) lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
  passenger (3.0.8) lib/phusion_passenger/spawn_manager.rb:132:in`spawn_application'
  passenger (3.0.8) lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
  passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:357:in`**send**'
  passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:206:in`start_synchronously'
  passenger (3.0.8) helper-scripts/passenger-spawn-server:99

Rendering /opt/redmine-1.2/public/500.html (500 Internal Server Error)

**Comment by ghost** [comment]
Ya. It does that with me too (minus the error).

Problems:
- When I create a new repository in the project settings repository tab, it doesn't create one.*
- The hooks weren't being copied to the new repositories either*
- When deleting the repository from the tab, it isn't removed from the gitolite_admin repo, and the bare git repo isn't removed as well

*Note, this was when I installed it WITH my repositories already up. I uninstalled the plugin, and reinstalled it with no repositories, and then I added a repository from the settings tab, and it created it, with the hooks, but there's no telling what will happen if I delete it. If I press the delete link, it will likely delete the database entry, but not the entry out of gitolite_admin repo, or the actual git repo; then after I click create again, nothing will happen; no new hooks getting copied over, and no new repo. If it is unsafe to delete the repo from gitolite_admin and the git repo when a user clicks delete on the repository, can a delete git repo option at least be provided? That way when you click create again it'll work properly.

**Comment by ericpaulbishop** [comment]
Try turning on the delete function in the plugin settings page.  It's disabled by default to keep you from accidentally deleting a repository you don't want to.

**Comment by ericpaulbishop** [comment]
czechbox:  What exactly is in your gitolite-admin repo?  If you manually clone it, do you see the conf/gitolite.conf file?

**Comment by czechbox** [comment]
Hi Eric,

here's whats in my local clone of the gitolite-admin repo:
dhcp61:gitolite-admin jef$ find ./
./
.//.DS_Store
.//.git
.//.git/branches
.//.git/COMMIT_EDITMSG
.//.git/config
.//.git/description
.//.git/FETCH_HEAD
.//.git/HEAD
.//.git/hooks
.//.git/hooks/applypatch-msg.sample
.//.git/hooks/commit-msg.sample
.//.git/hooks/post-commit.sample
.//.git/hooks/post-receive.sample
.//.git/hooks/post-update.sample
.//.git/hooks/pre-applypatch.sample
.//.git/hooks/pre-commit.sample
.//.git/hooks/pre-rebase.sample
.//.git/hooks/prepare-commit-msg.sample
.//.git/hooks/update.sample
.//.git/index
.//.git/info
.//.git/info/exclude
.//.git/logs
.//.git/logs/HEAD
.//.git/logs/refs
.//.git/logs/refs/heads
.//.git/logs/refs/heads/master
.//.git/logs/refs/remotes
.//.git/logs/refs/remotes/origin
.//.git/logs/refs/remotes/origin/master
.//.git/objects
.//.git/objects/02
.//.git/objects/02/c0b0234cda83e37c0ded5e67de0d37928ff38d
.//.git/objects/09
.//.git/objects/09/546b422aac9c2c365ad8e6afb75b4de9c6eaa4
.//.git/objects/24
.//.git/objects/24/ab7acdce526db881adf217bf957990584c2ae6
.//.git/objects/30
.//.git/objects/30/b0a4439903b21c98417e3d7c89339ca85728fd
.//.git/objects/31
.//.git/objects/31/67d308deaf45dffeead482c021c683420fd3b1
.//.git/objects/36
.//.git/objects/36/0a29ebc0d10ef27ee72b3ac68a0f06d40d5f8b
.//.git/objects/3a
.//.git/objects/3a/794f5f56bb2e285949e16ab2c2524cbf452ff9
.//.git/objects/3e
.//.git/objects/3e/0bea2f6653842e1bf3445066bddd62047f6d9b
.//.git/objects/41
.//.git/objects/41/f64d90d6effd8adf4c29532c96ccbbccda7d2f
.//.git/objects/50
.//.git/objects/50/9a7c6ec71deb4cfc91972f3449cb2a8778c63f
.//.git/objects/56
.//.git/objects/56/d427025eab8f0de47609d64e6b283f8ef77d65
.//.git/objects/65
.//.git/objects/65/ce3921d008fc1e61ce9e1e90bd86c4b7454f52
.//.git/objects/72
.//.git/objects/72/321415d7bbdcaa629940a31faf81993fae3b5e
.//.git/objects/af
.//.git/objects/af/95ac374f2907a05308e8805406838d6b8e5d1d
.//.git/objects/cd
.//.git/objects/cd/278157d8159c94da313c48b6277fd87cab0c76
.//.git/objects/d3
.//.git/objects/d3/e881b82fe63f82c32277d695129ba4094d35ff
.//.git/objects/fa
.//.git/objects/fa/a5e60c0c4628bdbf2318029a20363995321bc9
.//.git/objects/info
.//.git/objects/pack
.//.git/objects/pack/pack-e3690ca9a1d84cf3a81c0fb25d90be9aa7a3cdd6.idx
.//.git/objects/pack/pack-e3690ca9a1d84cf3a81c0fb25d90be9aa7a3cdd6.pack
.//.git/ORIG_HEAD
.//.git/packed-refs
.//.git/refs
.//.git/refs/heads
.//.git/refs/heads/master
.//.git/refs/remotes
.//.git/refs/remotes/origin
.//.git/refs/remotes/origin/HEAD
.//.git/refs/remotes/origin/master
.//.git/refs/tags
.//conf
.//conf/gitolite.conf
.//keydir
.//keydir/git.pub
.//keydir/jef.pub

as you can see, the gitolite.conf file is there

**Comment by ericpaulbishop** [comment]
I notice that your admin keys are git.pub and jef.pub.  Does one of those public key files match the public key for the one you set during the configuration?  What does your init.rb file look like?  In particular, do the specified filenames for the key files exist and correspond to the public keys git.pub or jef.pub?

**Comment by czechbox** [comment]
yep the git.pub file is the admin key, copies of both that public and the corresponding private key are installed in the redmine/.ssh folder 

Here's the init.rb settings:

settings :default => {
        'httpServer' => 'clients.XXXXXXX.com',
        'gitServer' => 'clients.XXXXXXX.com',
        'gitUser' => 'git',
        'gitRepositoryBasePath' => 'repositories/',
        'gitoliteIdentityFile' => RAILS_ROOT + '/.ssh/gitolite_id_rsa',
        'gitoliteIdentityPublicKeyFile' => RAILS_ROOT + '/.ssh/gitolite_id_rsa.pub',
        'allProjectsUseGit' => 'false',
        'deleteGitRepositories' => 'false',
        'gitRepositoriesShowUrl' => 'true',
        'gitCacheMaxTime' => '-1',
        'gitCacheMaxElements' => '100',
        'gitCacheMaxSize' => '16',
        'gitHooksDebug' => 'false',
        'gitHooksAreAsynchronous' => 'true'

**Comment by ericpaulbishop** [comment]
So you have files called git and git.pub in redmine/.ssh?  If so you need to edit your init.rb:

'gitoliteIdentityFile' => RAILS_ROOT + '/.ssh/git',
'gitoliteIdentityPublicKeyFile' => RAILS_ROOT + '/.ssh/git.pub',

Or did you rename them to gitolite_id_rsa when you copied them to redmine/.ssh (in which case the init.rb is correct)?

**Comment by czechbox** [comment]
I renamed them :)

**Comment by ericpaulbishop** [comment]
If you actually look in /tmp/redmine_git_hosting what is there?

**Comment by czechbox** [comment]
root@ip-10-128-190-138:/tmp/redmine_git_hosting# ll
total 20
drwx------ 2 www-data www-data 4096 2011-09-06 06:21 ./
drwxrwxrwt 6 root     root     4096 2011-09-06 07:01 ../
-r-xr-x--- 1 www-data www-data  110 2011-09-06 06:21 gitolite_admin_ssh*
-r-xr-x--- 1 www-data www-data  231 2011-09-06 06:21 run_as_git_user*
-r-xr-x--- 1 www-data www-data  171 2011-09-06 06:21 run_git_as_git_user*

**Comment by ericpaulbishop** [comment]
Ok try this:  
(1) su to become the www-data user 
(2) Run the following command:
env GIT_SSH='/tmp/redmine_git_hosting/gitolite_admin_ssh' git clone git@clients.XXXXXXX.com:gitolite-admin.git /tmp/redmine_git_hosting/gitolite-admin

What output do you get?

**Comment by czechbox** [comment]
Hmm... this seems odd:

Initialized empty Git repository in /tmp/redmine_git_hosting/gitolite-admin/.git/
Warning: Identity file /opt/redmine-1.2/.ssh/gitolite_id_rsa not accessible: Permission denied.
Could not create directory '/var/www/.ssh'.
Failed to add the host to the list of known hosts (/var/www/.ssh/known_hosts).
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

**Comment by ericpaulbishop** [comment]
Try running:
chown www-data -R /opt/redmine-1.2/.ssh/

Then try again.  If you get the same error run:
ls -l /opt/redmine-1.2/.ssh/*
and post the output here

**Comment by czechbox** [comment]
okay, figured out the permission error: redmine/.ssh was chmod 600, I've updated it to be 700

I ran the snippet you sent, no errors this time:

Initialized empty Git repository in /tmp/redmine_git_hosting/gitolite-admin/.git/
remote: Counting objects: 23, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 23 (delta 2), reused 0 (delta 0)
Receiving objects: 100% (23/23), done.
Resolving deltas: 100% (2/2), done.

However, it's still not updating the gitolite.conf file with new repositories when I add them in redmine

**Comment by ericpaulbishop** [comment]
Can you verify that you have not only created the Project, but the corresponding repository as well?  By default you have to go to the repository tab and create the repository for each project.  There is an option in the plugin to do this automatically, but it is off by default.

**Comment by czechbox** [comment]
Hi Eric,

I've tried both ways , with auto repo creation on (nothing happens) and with it turned off then adding the repo via the project settings.

**Comment by ericpaulbishop** [comment]
Can I assume you've set a public key for your Redmine/ChiliProject user?

**Comment by czechbox** [comment]
Yes, and now it seem to be adding in the repos, but only granting "read-only" permissions even though the user has "commit access":

repo    tribal
    R   =   jef

**Comment by ericpaulbishop** [comment]
. . . . in other words, no, you DIDN'T set a public key.  I'm not referring to the gitolite admin public key, but rather a public key for the user in Redmine who will have access to the project.  Login to Redmine, go to My Account in the upper right hand corner.  In the right column, enter your public key, which should be different from any public key already set.  Hit save, and the private key associated with the public key you set should now have access to any project that that user has permissions for.

**Comment by czechbox** [comment]
ah.. well yes and no. Yes the key was there, and mapped to that user, but not one that was setup in the redmine UI. This was also causing a conflict in authentication. Soo... I guess the lesson here is that you need to start with out existing users in the gitolite repo.

Thanks for your help sorting this out!
