### ISSUE TITLE
Severe errors migrating from gitosis 

### ISSUE THREAD

**Issue by juselius** [ericpaulbishop/redmine_git_hosting#74]
I recently migrated from redmine 1.1.3 + gitosis  to redmine 1.2.1 +
gitolite + redmine_git_hosting. This is a far better package in every
respect. Thank you very much for your work! However, in the upgrade I
stumbled upon the following issues (with version 0.3.0):

My old redmine_gitosis managed repos had absolute paths in
the redmine database. redmine_git_hosting uses paths relative to the git
user. In the upgrade the paths were not updated in the database, so that
redmine complained that no repositories were configured. I tried to
remedy the problem by changing the plugin setting from 'repositories/'
-> 'xrepositories/', in the hope that this would update the database (to
a faulty path, which could then be corrected back). The result was that
the whole passenger process crashed because of some 'nil' reference! (I
lost the traceback, sorry). I had to edit the redmine database by hand
in order to a) rectify the error b) migrate the repository paths.

**Comment by ericpaulbishop** [comment]
Migration from the gitosis plugin is NOT currently supported.

**Comment by juselius** [comment]
The "migration" worked fine, apart from the issue mentioned above. I didn't migrate any user settings or keys, just moved the repositories from gitosis to gitolite. I still suspect this is a nasty bug, but I have not tested it thoroughly. The gitosis and gitolite plugns share the 'repositories' table, but have different ideas of how to specify the base path. This is no problem, since changing the base path in the git_hosting config should sweep the table and update the records anyhow. Right? But instead it got a nill refernce and crashed the passenger. Problem solved by correcting 'repositories' "by hand". I realize that this is perhaps not a top issue, but is it _really_ supported to change the repository base path?
