### ISSUE TITLE
Paths not correctly updated in /tmp/redmine_git_hosting/

### ISSUE THREAD

**Issue by juselius** [ericpaulbishop/redmine_git_hosting#75]
(Only tested with 0.3.0)

Changing the gitolite ssh identity file in the plugin settings does
not take effect until a) the original /tmp/redmine_git_hosting dir is
deleted by hand (or a reboot) b) redmine is restarted.

Since /tmp/redmine_git_hosting/gitolite_admin_ssh contains the
wrong path, adding ssh public keys under "My Account" does not work: At
first you get an internal server error, and when you retry the error is
gone, but nothing happens.

**Comment by ericpaulbishop** [comment]
This should be fixed in 0.4.0.  You're welcome to use 0.3.0, but I'm not going to provide support for it.

**Comment by juselius** [comment]
I am on 0.4.0, but I triggered the issue while on 0.3.0. I just didn't have time to report it then ;) I can confirm that it works now. 

Btw, thank you for very nice work in general! Much appreciated!
