### ISSUE TITLE
calls to project.repository.extras crash plugin

### ISSUE THREAD

**Issue by Jehreg** [ericpaulbishop/redmine_git_hosting#78]
I installed Gitosis, and the plug-in. I created a new project, non-public.
2 things:
1. The repository is never created from me.  No errors appear in the production log
2. When you ask to view the Overview of the project, I get a crash at any read of the project.repository.extra variable:

```
ActionView::TemplateError (undefined method `[]' for nil:NilClass) on line #30 of vendor/plugins/redmine_git_hosting/app/views/projects/_git_urls.erb:
27:                     <% if !User.current.anonymous? %>
28:                         <li><a id="git_url_ssh"  href="javascript:void(0)">SSH</a></li>
29:                     <% end %>
30:                     <% if project.repository.extra[:git_http].to_s != "0" %>
31:                         <li><a id="git_url_http" href="javascript:void(0)">HTTP</a></li>
32:                     <% end %>
33:                     <%  if project.is_public && project.repository.extra[:git_daemon].to_s != "0" %>

    vendor/plugins/redmine_git_hosting/app/views/projects/_git_urls.erb:30
    lib/redmine/hook.rb:109:in `send'
    lib/redmine/hook.rb:109:in `view_projects_show_left'
    lib/redmine/hook.rb:59:in `send'
    lib/redmine/hook.rb:59:in `call_hook'
    lib/redmine/hook.rb:59:in `each'
    lib/redmine/hook.rb:59:in `call_hook'
    lib/redmine/hook.rb:56:in `tap'
    lib/redmine/hook.rb:56:in `call_hook'
    lib/redmine/hook.rb:140:in `call_hook'
    app/views/projects/show.rhtml:50:in `_run_rhtml_app47views47projects47show46rhtml'
    app/controllers/projects_controller.rb:146:in `show'
    /usr/lib/ruby/1.8/phusion_passenger/rack/request_handler.rb:95:in `process_request'
.....
```

**Comment by ericpaulbishop** [comment]
Errr.. this plugin requires gitolite, not gitosis.

**Comment by ericpaulbishop** [comment]
I'm going to close this for now -- once you've installed the proper required software and tried again, you can re-open if you still have a problem.

**Comment by Jehreg** [comment]
Sorry, I did install Gitolite, not Gitosis.  The error still stands :-)

**Comment by ericpaulbishop** [comment]
Ok, what was the output, specifically, when you ran the migration command?

**Comment by Jehreg** [comment]
Oh boy, I closed that window a while ago.  There was no errors on migration as I recall.  I am working on a recipe for installing Chili+ this plugin, so I started with a fresh install of Chili: no previous projects nor repositories.

I can start over from the top if you wish and provide all output, but I cannot do this before tomorrow morning.

**Comment by ericpaulbishop** [comment]
Hmm.. if you're starting from a clean install it might not be obvious what's going on from the migration.  What version of ChiliProject are you using?

**Comment by Jehreg** [comment]
Chili v2.2.x branch.

BTW, I am getting this error after creating a new project, not from a project that was present before I installed the plugin.

**Comment by ericpaulbishop** [comment]
I've mostly been testing with ChiliProject 2.0.0.  I'll try 2.2.0 and see if I can reproduce the problem.

**Comment by ericpaulbishop** [comment]
I just tested with 2.2.0, and it seems to work fine, so I don't think it's the version you're using.  If you go into your database, can you let me know what tables you see?  I want to know if the extras table got created properly during the migration

**Comment by Jehreg** [comment]
I will re-install from scratch today, and re-test. If it doesn't work, I will post a recipe in here that I followed to create the setup.

**Comment by Jehreg** [comment]
OK, after a full re-install, I get:

Processing ProjectsController#create (for 10.0.2.2 at 2011-09-08 12:44:39) [POST]
  Parameters: {"commit"=>"Save", "action"=>"create", "authenticity_token"=>"pT5+NNdE5DtK8++62XDNw+ckvTXB17Z5hDIcOLeYlgo=", "project"=>{"name"=>"test1", "tracker_ids"=>["1", "2", "3", ""], "homepage"=>"", "is_public"=>"0", "description"=>"test1", "identifier"=>"test1", "enabled_module_names"=>["issue_tracking", "time_tracking", "news", "documents", "files", "wiki", "repository", "boards", "calendar", "gantt", ""]}, "controller"=>"projects"}
Redirected to http://127.0.0.1:8080/projects/test1/settings
Cloning gitolite-admin repository
Our hook is already installed

NoMethodError (undefined method `git_daemon' for nil:NilClass):
  vendor/plugins/redmine_git_hosting/app/models/git_hosting_observer.rb:78:in`update_repositories'
  vendor/plugins/redmine_git_hosting/app/models/git_hosting_observer.rb:39:in `after_create'
  /usr/lib/ruby/1.8/observer.rb:185:in`notify_observers'
  /usr/lib/ruby/1.8/observer.rb:184:in `each'
  /usr/lib/ruby/1.8/observer.rb:184:in`notify_observers'
  /usr/lib/ruby/1.8/phusion_passenger/rack/request_handler.rb:95:in `process_request'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_request_handler.rb:207:in`main_loop'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:374:in `start_request_handler'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:332:in`handle_spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/utils.rb:184:in `safe_fork'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:330:in`handle_spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `__send__'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in`main_loop'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:163:in`start'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:209:in `start'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:262:in`spawn_rails_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:126:in `lookup_or_add'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:256:in`spawn_rails_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:80:in `synchronize'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:79:in`synchronize'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:255:in `spawn_rails_application'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:154:in`spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:287:in `handle_spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in`**send**'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `main_loop'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in`start_synchronously'
  /usr/lib/phusion_passenger/passenger-spawn-server:61

Rendering /var/www/rails_apps/chili/public/500.html (500 Internal Server Error)

If I install a git public daemon, will this just start working ?

**Comment by ericpaulbishop** [comment]
I think I found the problem, testing a solution now.

**Comment by Jehreg** [comment]
So, it just dawn on me that git_daemon is a table column...

Looking at the DB I see that repositories_extras doesn't exist.

I re-installed everything from scratch and ran the migrate script with trace on:

Migrating plugin redmine_git_hosting ...
==  ExtendChangesetsNotifiedCia: migrating ====================================
-- add_column(:changesets, :notified_cia, :integer, {:default=>0})
   -> 0.1237s
==  ExtendChangesetsNotifiedCia: migrated (0.1239s) ===========================

==  CreateRepositoryMirrors: migrating ========================================
-- create_table(:repository_mirrors)
   -> 0.0346s
==  CreateRepositoryMirrors: migrated (0.0347s) ===============================

==  CreateGitRepositoryExtras: migrating ======================================
-- create_table(:git_repository_extras)
   -> 0.0150s
-- columns(:repositories)
   -> 0.0015s
-- columns(:repositories)
   -> 0.0011s
==  CreateGitRepositoryExtras: migrated (0.2144s) =============================

==  MoveNotifiedCiaToGitCiaNotifications: migrating ===========================
-- create_table(:git_cia_notifications)
   -> 0.0164s
-- add_index(:git_cia_notifications, :scmid)
   -> 0.0300s
-- add_index(:git_cia_notifications, [:scmid, :repository_id], {:unique=>true})
   -> 0.0237s
-- columns(:changesets)
   -> 0.0011s
-- remove_column(:changesets, :notified_cia)
   -> 0.0264s
==  MoveNotifiedCiaToGitCiaNotifications: migrated (0.1001s) ==================

==  SetMirrorRolePermissions: migrating =======================================
==  SetMirrorRolePermissions: migrated (0.0686s) ==============================

==  CreateGitolitePublicKeys: migrating =======================================
-- create_table(:gitolite_public_keys)
   -> 0.0146s
==  CreateGitolitePublicKeys: migrated (0.0147s) ==============================

==  CreateGitCaches: migrating ================================================
-- create_table(:git_caches)
   -> 0.0161s
==  CreateGitCaches: migrated (0.0162s) =======================================

**Comment by Jehreg** [comment]
If I set auto-create on, and then create a new project with Non-public access, I get the error pretty much 100%

**Comment by Jehreg** [comment]
I hope this is related:

Default install, no existing projects.
Plugin config is set to no auto-create, no auto-delete, everything else is stock.

RELOAD APACHE

Create new project, set repo as GIT, click Create

You will see the repo created in /home/git/repository/

Create ANOTHER project, set repo as GIT, click Create

No repo will be created in /home/git/repository/ this time.

Try creating another one... still nothing.

RELOAD APACHE

Create a new project, set repo as GIT, click on Create.

Now this one appears in /home/git/repositories, and some other ones may now start appearing.

**Comment by Jehreg** [comment]
So, to summerize, only the project created immediately after an Apache Reload will create a repository in /home/git/repositories

**Comment by ericpaulbishop** [comment]
This should now be fixed.

**Comment by Jehreg** [comment]
Confirmed fixed, thanks.
