### ISSUE TITLE
gitolite private key is exposed

### ISSUE THREAD

**Issue by juselius** [ericpaulbishop/redmine_git_hosting#81]
When creating a new git repository, the following command is executed:

sh -c /tmp/redmine_git_hosting/run_as_git_user 'echo "CONTENTS OF GITOLITE PRIVATE KEY IN PLAIN TEXT " > ~/.ssh/gitolite_admin_id_rsa'

This exposes the passwordless private key to any user with access to the machine, effectively granting them full access to all repositories hosted under gitolite. There are two simple solutions to this problem: 

a) Let the admin take responsibility for the keys! There is as far as I can tell no need to copy any gitolite keys when a repository is created
b) Use 'cp' instead if 'echo'.

**Comment by ericpaulbishop** [comment]
Should be fixed now
