### ISSUE TITLE
Add documentation note about deleting repositories

### ISSUE THREAD

**Issue by ghost** [ericpaulbishop/redmine_git_hosting#83]
This should be fairly simple, but a few people have had misunderstandings on this (including me).

A simple note in the documentation explaining that the deleting repositories option is disabled by default (and why), and what it does when it's enabled (for clarification), and possibly how to enable it.

If you want, you could also explain the auto create feature, although not technically needed.

Also, the reason I was confused, is that the setting in the configuration is somewhat misleading.

"Delete Git Repository When Project is Deleted" - This led me to believe that it deletes when the project is deleted, but not when you actually press the delete link in the project settings repository tab. Which is why I didn't enable it, and made a bug report.

**Comment by ericpaulbishop** [comment]
Done -- now mentioned in step (9) of install, where other, optional variables are discussed.
