### ISSUE TITLE
Question: making repo available by git-daemon

### ISSUE THREAD

**Issue by Jehreg** [ericpaulbishop/redmine_git_hosting#84]
I have the plugin pretty much figured out now, and I have installed git-daemon to provide non-auth access to the repos.

I have created a public repo, and gitolite has it defined in /home/git/repositories/

When I try to access it using "git clone git:" the git-daemon log tells me:

2011-09-08_23:19:16.52958 [11309] Request upload-pack for '/test100.git'
2011-09-08_23:19:16.52973 [11309] '/home/git/repositories/test100.git': repository not exported.
2011-09-08_23:19:16.53128 [11303] [11309] Disconnected (with error)

If I put a file called "git-daemon-export-ok" in /home/git/repositories/test100.git/ everything works fine.

I did not find that string anywhere in the plugin, so I imagine that some other mechanism may be in play when a repository is flagged as "Git Daemon: Enabled", but I could not figure it out by looking at the plugin docs.

Please advise.

**Comment by ericpaulbishop** [comment]
Is the project public?  If not, git daemon availability isn't set even if you toggle it in the repository settings, since by definition the git:// protocol is public.

**Comment by Jehreg** [comment]
The git:// protocol is public, but git demon won't export/give-access-to the repo unless that file is there.  Maybe that changed in git since you last tried it ?

**Comment by Jehreg** [comment]
Please refer to commit id 8b2bd7cdacf71260dbc954316af2bed8e076c182 in the git source code.

It's not available on kernel.org right now, so check git/git on Github.

**Comment by ghost** [comment]
> The git:// protocol is public, but git demon won't export/give-access-to the repo unless that file is there. Maybe that changed in git since you last tried it ?

He means, is your _Redmine_ project public. Redmine projects can be either public or private, and if the project is private, git daemon isn't available for it, since the repo would be made publicly available to anyone, which would be a security risk.

As for enabling the feature. Go to your project in Redmine, then click the settings tab, then click "Repositories", and you'll see under Repository Options, "Git Daemon", with a Enabled or Disabled dropdown menu.

**Comment by Jehreg** [comment]
My Redmine project is public.  Git Deamon is "Enabled".

**Comment by ericpaulbishop** [comment]
In that case the next step is to take a look in your gitolite-admin config file.  Look in /tmp/redmine_git_hosting/gitolite-admin/conf/gitolite.conf.  Look for a line in that file that says "R = daemon" under your repo.  That line should tell gitolite to make the repo public (gitolite should create the proper file in the git directory in response to that line), so this is done a bit indirectly so we can control everything through gitolite.

**Comment by Jehreg** [comment]
OK, looking at the /tmp/ dir, I have:

root@chili:/tmp# find ./redmine_git_hosting -print
./redmine_git_hosting
./redmine_git_hosting/run_as_git_user
./redmine_git_hosting/run_git_as_git_user
./redmine_git_hosting/gitolite_admin_ssh

So, no gitolite-admin subdir.

I did a git clone git@127.0.0.1:gitolite-admin, and checked out that file, I have:

repo    gitolite-admin
    RW+ =   gitolite_admin_id_rsa

repo    test100
    R   =   gitolite_admin_id_rsa

repo    testpriv
    R   =   gitolite_admin_id_rsa

In Chili, "test100" is public and "testpriv" is private. Any other info I can provide ?

**Comment by Jehreg** [comment]
Wait.  I just added my first non-admin user, added an SSH key and now that directory appears with correct content:

root@chili:/tmp/redmine_git_hosting/gitolite-admin/conf# cat gitolite.conf 
repo    gitolite-admin
    RW+ =   gitolite_admin_id_rsa

repo    test100
    R   =   daemon

repo    testpriv
    RW+ =   redmine_patrickn_1315842794_372138

I wonder under which conditions does the code 

   #git daemon
   if (project.repository.extra.git_daemon == 1 || project.repository.extra.git_daemon == nil )  && project.is_public
       read_user_keys.push "daemon"
   end

get fired off...

  projects.select{|p| p.repository.is_a?(Repository::Git)}.each do |project|

Hmmm, does that fire off if no push had already been done ?

I may have to reset and see under what exact condition the proper subdir and setting gets created.

**Comment by ericpaulbishop** [comment]
I'm going to close this issue for now.  It sounds like you got it working, and I can't reproduce the problem.  If you come up with a way to reproduce this consistently, let me know.
