### ISSUE TITLE
Disabling "Show checkout URL's" option still shows checkout URL

### ISSUE THREAD

**Issue by ghost** [ericpaulbishop/redmine_git_hosting#85]
After disabling that option, I still saw the checkout URL stuff displaying on the main project index page. It however did disappear on the Repository tab when I disabled it. I logged out, and I can still see it on the project index page.

I've been playing around with the plugin code (integrating ZeroClipboard), so it's possible it's a problem I created, but I don't think it is.

Speaking about ZeroClipboard. It works wonderfully for me after I finished it. I then added a setting for it in the plugin control panel, but the setting is always evaluating to True for some reason (so I can't turn the feature off). I was going to send a pull request with the feature after I was done, but I can't get that part working. Mind if I send you the request, then you can fix that part? I'm not a Redmine/Ruby/Redmine_Git_Hosting expert, so I can imagine it's probably a simple thing.

**Comment by ericpaulbishop** [comment]
I'll look into the issue with visualizing the checkout URLs.  In the mean time, why don't you fork my repo on github and add your code -- then we can discuss your actual code, and it will be easier for merge when you're ready.

**Comment by ericpaulbishop** [comment]
This looked to be working in the repository tab, but not the overview tab.  I just committed an update so that this setting controls display in the overview tab too, so it should be fixed now.

As noted in your pull request, your zero clipboard code is now merged (and included in 0.4.2, just released)
