### ISSUE TITLE
User id interferes with gitolite

### ISSUE THREAD

**Issue by juselius** [ericpaulbishop/redmine_git_hosting#87]
I earlier filed a feature request (#77) for supporting gitolite multikeys. I have since noticed the following problem with users who have registered with an e-mail address as their user id: Since the user id has an @ in it, gitolite will treat it as multikey effectively turning the part leading up to the @ as the user name, and ignoring the rest. This causes gitolite to complain every time the repository is pushed:

remote: 
remote:         ****\* WARNING *****
remote:         the following users (pubkey files in parens) do not appear in the config file:
....

I have not tested it, but I suspect that the relevant users are not able to access the repositories correctly either. I will test this later.

**Comment by ericpaulbishop** [comment]
I've updated the code so "@" characters get replaced with "_" when converting user ids to key ids.  This should fix the problem.
