### ISSUE TITLE
create new project with identifier of an existing gitolite repo

### ISSUE THREAD

**Issue by kyse** [ericpaulbishop/redmine_git_hosting#9]
When you create a new project with an identifier of an existing repo in gitolite, it brings you to an error page where you have to hit back.  It doesn't tell you the reason, but I assumed, and am guessing the repo already existing is the cause.  Should have a page come up instead that gives two options.
1) don't create the proejct yet, first check to see if the repo exists, if so, notify the user and allow him to change the idenfitier before proceeding with project creation, if that identifier isn't also an existing repo.
2) same as above, except instead of using a new identifier, allow the project creation to proceed and instead of creating the new repo, just update the existing repo to include whatever rights the plugin requires to do it's thing so the repo tab points correctly.

**Comment by TheEmpty** [comment]
I didn't have a problem :-/

**Comment by kyse** [comment]
Nod, I tested it again and didn't get the same error page, I don't know what
it was now.  Oh well.  Still hoping to get my redmine repository to show
finally, sigh.

**Comment by ericpaulbishop** [comment]
I couldn't replicate this issue either, I'm going to close it -- feel free to comment/reopen if you encounter the problem again.

**Comment by kwisatz** [comment]
I experienced the same issue, but the other way around:

Creating a new repository with the same name than an existing project would result in 
**Identifier cannot match identifier of existing project**

Why can a repository not have the same identified than a project? Are they using the same table with the data having that identifier as a primary key?

**Comment by a-stangl** [comment]
Same here, trying to add an existing repo to an already existing project results in
     `Identifier cannot match identifier of existing project`
What to do?
