### ISSUE TITLE
Post-receive hook error with Redmine not in root URL

### ISSUE THREAD

**Issue by frasten** [ericpaulbishop/redmine_git_hosting#90]
I have Redmine installed in `http://myserver/redmine/`, and I couldn't see my commits imported into Redmine.
After a bit of research, I discovered that the git variable "hooks.redmine_gitolite.url" was set to `http://myserver/githooks/post-receive`, and that couldn't work because my Redmine installation is not in the root directory of the webserver.
The culprit is this line in lib/git_adapter_hooks.rb:

``` ruby
hook_url = "http://" + Setting.plugin_redmine_git_hosting['httpServer'] + "/githooks/post-receive"
```

**Comment by ericpaulbishop** [comment]
httpServer should include full path to Redmine root.  I've updated the README to reflect this.
