### ISSUE TITLE
Variables in gitolite.conf get lost

### ISSUE THREAD

**Issue by dfyx** [ericpaulbishop/redmine_git_hosting#91]
Because this plugin just drops lines from gitolite.conf that it doesn't understand, variable definitions (for example for developer groups) get lost.

I might fix this myself if I find the time but that might take a while.

**Comment by ericpaulbishop** [comment]
You are correct that this can happen because the plugin doesn't make use of all the features gitolite has to offer.

I would welcome your help with this -- contributions are very welcome -- but for now I consider this a feature request rather than a bug, and I'm going to close the issue.
