### ISSUE TITLE
authorized_keys file.

### ISSUE THREAD

**Issue by ackiejoe** [ericpaulbishop/redmine_git_hosting#93]
I've setup chiliproject, gitolite, and redmine_git_hosting but chiliproject is still not writing to the authorized_keys file when I add a users key, I'm not seeing an errors anywhere and all tests I do seem to work fine. My question is where in the code does the actual writing to the authorized_keys file take place? if I can fine that and see how it is trying to do it, I should be able to resolve my problem.

Thanks in advance.

.Ak

**Comment by ericpaulbishop** [comment]
It doesn't modify the authorized_keys file directly, it does so indirectly by modifying the admin repo of gitolite, which then modifies the authorized_keys file for the git user when the admin repo gets pushed.  The key code for managing this is in lib/git_hosting.rb and lib/gitolite_conf.rb

**Comment by ericpaulbishop** [comment]
I'm going to close this issue for now.  If you continue having problems, feel free to reopen it with more details of the problem.

**Comment by rcross** [comment]
I'm having a similar problem. 

Is there a way to regenerate the gitolite configuration file(s)? or somehow check the configuration against the permissions in the redmine db? 

It appears that keys that are deleted, are not deleted from the configuration which is causing some issues.
