### ISSUE TITLE
error in git_hosting_settings_observer.rb

### ISSUE THREAD

**Issue by rchady** [ericpaulbishop/redmine_git_hosting#96]
Hello,

First off, great work on this.  I believe I stumbled on a bug when testing out changing the gitRepositoryBasePath though.  The error is in git_hosting_settings_observer.rb:27 where it references "project.each" when I believe it should be "all_projects.each".

**Comment by ericpaulbishop** [comment]
You're absolutely right, fix should now be committed.  Thanks!
