### ISSUE TITLE
Groups defined in gitolite.conf being stripped?

### ISSUE THREAD

**Issue by rchady** [ericpaulbishop/redmine_git_hosting#97]
I have some projects being managed in gitolite that are not in ChiliProject.  Because of this, I have some groups defined, I'll talk about one here - @git_admins.  When this plugin runs, it rebuilds the config file and is stripping the definition of the groups at the top of the file.  The access control is still listed referencing @git_admins, but the definition no longer exists in the file.

Partly because of this and partly for organizational reasons, I wonder if it would be easier to leave gitolite.conf alone and build a file that is then included in gitolite.conf instead?  I would expect this to actually be easier for you to do and lowers the risk of something else getting clobbered.

**Comment by ericpaulbishop** [comment]
There are a number of ways of addressing this issue, but you're right that the current scheme can cause this problem with other, existing gitolite configuration options.

I consider this less of a "bug" than a feature request, though.  If you'd like to work on it, and submit a patch I'd be more than happy to accept your contribution, but this really isn't a high priority for me right now.

**Comment by rchady** [comment]
I agree, putting all of this in a separate file is a feature request.  The stripping of the already defined groups I considered a bug.  Unfortunately I am not aware of a way to file a feature request other than classify it as an issue in github's setup.

**Comment by sboisson** [comment]
I had the same problem and I solved it with a patch
See https://github.com/ericpaulbishop/redmine_git_hosting/pull/102
